# Use uma imagem oficial do Node.js
FROM node:16

# Crie o diretório de trabalho
WORKDIR /app

# Copie o package.json e instale as dependências
COPY package*.json ./
RUN npm install

# Copie o código do projeto
COPY . .

# Exponha a porta da aplicação
EXPOSE 8080

# Comando para rodar o backend
CMD ["npm", "start"]
